name: Build and Deploy to gh-pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Roda direto na raiz, sem 'cd client'
      - name: Install Dependencies 📦
        run: npm install

      # Executa o build padrão do seu package.json
      - name: Build Project 🏗️
        run: npm run build

      # Faz o deploy da pasta compilada
      - name: Deploy to gh-pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true

